include "muxes.sk";
include "rel_ops.sk";
include "constants.sk";

StateResult atom_template(int state_1, int state_2, int pkt_1, int pkt_2, int pkt_3, int pkt_4, int pkt_5) {
  if (rel_op(mux2(state_1, 0), mux3(pkt_1, pkt_2, CONST()))) {
    state_1 = mux2(state_1, 0) + mux3(pkt_1, pkt_2, CONST());
  }
  StateResult ret = new StateResult();
  ret.result_state_1 = state_1;
  ret.result_state_2 = state_2;
  return ret;
}
