include "muxes.sk";
include "rel_ops.sk";
include "constants.sk";

StateResult atom_template(int state_1, int state_2, int pkt_1, int pkt_2) {
  if (rel_op(Opt(state_1), Mux3(pkt_1, pkt_2, C()))) {
    state_1 = Opt(state_1) + Mux3(pkt_1, pkt_2, C());
  } else {
    state_1 = Opt(state_1) + Mux3(pkt_1, pkt_2, C());
  }
  StateResult ret = new StateResult();
  ret.result_state_1 = state_1;
  ret.result_state_2 = state_2;
  return ret;
}
